//Initialisierung der Sensoren und Motoren mit Standardbelegung
#pragma config(Sensor, S1,     touchSensor,   sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,    sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,   sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,   sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA, armMotor,      tmotorEV3_Medium, PIDControl,             encoder)
#pragma config(Motor,  motorB, leftMotor,     tmotorEV3_Large,  PIDControl, driveLeft,  encoder)
#pragma config(Motor,  motorC, rightMotor,    tmotorEV3_Large,  PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Kann auch über "Motor and Sensor Setup"-Button oder Codeanpassung verändert werden

/*
Autor:               Bock/Feike/Henning
Pfad/Datei:          start.c
Zugehörig zu:        Einfuehrung in LEGO Mindstorms EV3
Beschreibung:        Erstes Programm in ROBOTC
Erstelldatum:        2018-02-12
*/

task main()
{
	bool bTouch = false;
	float fDist = 0.0;
	while(true)
	{
		bTouch = getTouchValue(S1);
		fDist = getUSDistance(S4);
		if (!bTouch)
		{
			if (fDist >= 20)
			{
				setMotorSpeed(motorB, 100);
				setMotorSpeed(motorC, 100);
			}
			else
			{
				setMotorSpeed(motorB, 20);
				setMotorSpeed(motorC, 20);
			}
		}
		else
		{
			setMotorSpeed(motorB, -50);
			setMotorSpeed(motorC, -50);
			sleep(300);
			setMotorSpeed(motorB, -50);
			setMotorSpeed(motorC, 50);
			sleep((rand() % 500) + 300);
		}
	}
}
