//Initialising Motors
#pragma config(Sensor, S1,     touchSensor,   sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,    sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,   sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,   sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA, armMotor,      tmotorEV3_Medium, PIDControl,             encoder)
#pragma config(Motor,  motorB, leftMotor,     tmotorEV3_Large,  PIDControl, driveLeft,  encoder)
#pragma config(Motor,  motorC, rightMotor,    tmotorEV3_Large,  PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Author:               Jorik Cronenberg
*/

task main()
{
	float fDist = 0.0;
	while(true)
	{
		fDist = getUSDistance(S4);
			if (fDist >= 25)
			{
				setMotorSpeed(motorB, 100);
				setMotorSpeed(motorC, 100);
			}
			else if(fDist >= 10)
			{
				setMotorSpeed(motorB, 20);
				setMotorSpeed(motorC, 20);
			}
			else
			{
				setMotorSpeed(motorB, -50);
				setMotorSpeed(motorC, -50);
				sleep(300);
				setMotorSpeed(motorB, -50);
				setMotorSpeed(motorC, 50);
				sleep((rand() % 500) + 300);
			}
	}
}
